# Generated by Django 5.1.6 on 2025-02-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quetion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quetion_text',
            new_name='question_text',
        ),
    ]
